AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
  CacheRootDirectory: '../../tmp'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  MinSize: 3

Style/SymbolProc:
  IgnoredMethods: validate

Style/Documentation:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Metrics/LineLength:
  Max: 89

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: 'ignore_implicit'

Layout/AlignParameters:
  Enabled: false
