default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', '') %>
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', ENV['USER']) %>
  password: <%= ENV.fetch('DB_PWD', '') %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'rails_template_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME_TEST', 'rails_template_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'rails_template') %>
